on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Add session token here
          aws-region: us-east-1

      - name: Install AWS SAM CLI
        run: |
          curl -Lo sam.tar.gz https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.tar.gz
          tar -xzf sam.tar.gz -C /usr/local/bin
          rm sam.tar.gz

      # Check SAM CLI Version
      - name: Verify SAM CLI installation
        run: sam --version

      # Build with SAM
      - name: Build with SAM CLI
        run: sam build

      # Validate the SAM template
      - name: Validate SAM template
        run: sam validate

      # Deploy the SAM application
      - name: Deploy with SAM CLI
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
